version: "3"
services:
  bottomtext:
    image: jokil/bottomtext:latest
    ports:
      - "80:3030"
    environment:
      - DB_PATH=/db_data/db
    volumes:
      - db_data:/db_data
    restart: unless-stopped
volumes:
  db_data:
