FROM rust:1.65

RUN cargo install trunk
RUN rustup target add wasm32-unknown-unknown

COPY common common

RUN cargo new --bin ui

WORKDIR /ui

COPY ui/Cargo.toml Cargo.toml
RUN cargo build --release
RUN rm src/*.rs

COPY ui .

RUN rm ./target/release/deps/ui*
RUN trunk build --release

EXPOSE 8080

CMD trunk serve --no-default-features --release