FROM rust:1.65

RUN cargo new --bin api
WORKDIR ./api
COPY ./Cargo.toml ./Cargo.toml
RUN cargo build --release
RUN rm src/*.rs

ADD . ./

RUN rm ./target/release/deps/api*
RUN cargo build --release



# # WORKDIR 
# COPY . .

# RUN cargo install --path ./api

EXPOSE 3030

CMD cargo run