FROM rust:1.65

COPY common common

RUN cargo new --bin api

WORKDIR /api

COPY api/Cargo.toml Cargo.toml
RUN cargo build --release
RUN rm src/*.rs

COPY api .

RUN rm ./target/release/deps/api*
RUN cargo build --release

EXPOSE 3030

CMD cargo run --release