[serve]
address = "0.0.0.0"
port = 8080
# no_autoreload = true

# [watch]
# ignore = ["../api/db"]

[[proxy]]
rewrite = "/api/ws"
backend = "ws://127.0.0.1:3030/ws"
ws = true

[[proxy]]
rewrite = "/api/frames"
backend = "http://127.0.0.1:3030/frames"