[serve]
# address = "0.0.0.0"
port = 8080
# no_autoreload = true

# [watch]
# ignore = ["../api/db"]

[[proxy]]
rewrite = "/api/ws"
backend = "ws://localhost:3030/ws"
ws = true

[[proxy]]
rewrite = "/api/frames"
backend = "http://localhost:3030/frames"

# [[hooks]]
# stage = "pre_build"
# command = "tailwindcss"
# command_arguments = ["-o","public/tailwind.css"]